### ISSUE TITLE
Select app to open a file dinamically

### ISSUE THREAD

**Issue by nivalderramas** [andersju/zzzfoo#10]
Hi, is there anyway to select the app that is going to open the file dinamically (when I find the file) or something similar? 
Thanks

**Comment by andersju** [comment]
You can use `-o <program>` to specify a certain program. In e.g. most Linux environments, `xdg-open <file>` will open the specified file using the default application for that particular file type. So you can do `zzzfoo -o xdg-open`. If you're using macOS, I believe the equivalent is `open`.

For information on how to check/set default applications from the command line, see https://wiki.archlinux.org/index.php/Xdg-utils (Arch wiki, but applicable to most other distributions). If you're using a desktop environment there's probably a GUI way to do the same thing.

**Comment by nivalderramas** [comment]
Thanks a lot man! Your app is great
