### ISSUE TITLE
When will it stop being considered "experimental", and have a version number?

### ISSUE THREAD

**Issue by ArnauBigas** [andersju/zzzfoo#3]
Hello!
I tried this program and it seems rather useful, I quite liked it.
I was thinking about making an archlinux aur package for this (since there isn't one currently), but then I noticed there is no version number which I assume is because you consider it to be "experimental". However, there haven't been any changes in a while and it seems stable enough (in my opinion).
Are there any issues I haven't noticed? For how long do you expect it to remain in this state?
Thanks.

**Comment by andersju** [comment]
I'm glad you find it useful/stable! I haven't noticed any issues, I just didn't bother adding a version until now :) Here you go: https://github.com/andersju/zzzfoo/releases/tag/v0.1

**Comment by ArnauBigas** [comment]
Cool, thanks!
