### ISSUE TITLE
Opening files fails silently

### ISSUE THREAD

**Issue by meesvermeulen** [andersju/zzzfoo#6]
With the command
```
zzzfoo --open-with=xdg-open
```
Nothing happens when accepting/pressing enter on a match.
I noticed that it does work for if I remove the ```stdout=PIPE, stderr=PIPE``` arguments at [line 215](https://github.com/andersju/zzzfoo/blob/master/zzzfoo#L215).

**Comment by andersju** [comment]
Strange! On the other hand `stdout=PIPE, stderr=PIPE` shouldn't be necessary there anyway, so I removed it. Thanks for reporting!
