### ISSUE TITLE
Only shows results when called with an argument

### ISSUE THREAD

**Issue by belugame** [andersju/zzzfoo#8]
First of all, thank you for your work :)
I have installed all and done my index and it works well when I call it with an argument. E.g. `./zzzfoo account` will show me a full list of results. But when I start it without argument I only see the rofi screen which says "Search:" and otherwise a popup. And I get nothing when I type e.g again "account".

**Comment by andersju** [comment]
Hmm, that's strange. If you start the program from the terminal, do you see any output (errors, warnings, notices etc)? What's your environment (OS / distribution, rofi version)?

**Comment by belugame** [comment]
Ok, my mistake :)

I did not realize that I'm supposed to press <Enter> after I typed a initial search term and only then it will start to show me results. I am too used to opening applications with rofi where it right away shows a list of applications and filters right away.
It works now, thank you :)

```
 rofi -v                                      
Version: 1.5.4
uname -a && lsb_release -dr
Linux Foo 5.6.0-1-amd64 #1 SMP Debian 5.6.7-1 (2020-04-29) x86_64 GNU/Linux
Description:    Debian GNU/Linux bullseye/sid
Release:        unstable
```
